spring:
  application:
    name: media-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mediadb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  swagger-ui:
    enabled: true
    path: /media-docs.html

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, info
